name: 'Major Release Tagger GitHub Action'
description: 'Major Release Tagger GitHub Action'
author: hello@cloudposse.com
branding:
  icon: 'file'
  color: 'white'
inputs:
  log-level:
    description: "Log level for this action. Available options: ['off', 'fatal', 'error', 'warn', 'info', 'debug']. Default 'info'"
    required: false
    default: 'info'
outputs:
  response:
    description: "Response"
    value: ${{ steps.run_tagger.outputs.response }}
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Setup Git Config
      shell: bash
      run: |
        git config --global user.name 'actions-bot'
        git config --global user.email 'actions-bot@users.noreply.github.com'

    - name: Install Node Dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npm install

    - name: Run Major Release Tagger
      shell: bash
      id: run_tagger
      run: |
        cd ${{ github.action_path }}
        export LOG_LEVEL='${{ inputs.log-level }}'
        node index.js $GITHUB_WORKSPACE

    - name: Get the output
      shell: bash
      run: |
        echo "${{ steps.run_tagger.outputs.response }}"
