name: 'Major Tag Releaser GitHub Action'
description: 'Major Tag Releaser GitHub Action'
author: hello@cloudposse.com
branding:
  icon: 'file'
  color: 'white'
outputs:
  response:
    description: "Response"
    value: ${{ steps.run_tagger.outputs.response }}
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Node Dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npm install

    - name: Run Major Release Tagger
      shell: bash
      id: run_tagger
      run: |
        cd ${{ github.action_path }}
        node index.js $GITHUB_WORKSPACE

    - name: Get the output
      shell: bash
      run: |
        echo "The output is: ${{ steps.run_tagger.outputs.response }}"
