name: 'Major Tag Releaser GitHub Action'
description: 'Major Tag Releaser GitHub Action'
author: hello@cloudposse.com
branding:
  icon: 'file'
  color: 'white'
outputs:
  result:
    description: "Result"
    value: ${{ steps.affected.outputs.result }}
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Node Dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npm install

    - name: Run Release Branch Manager
      shell: bash
      run: |
        cd ${{ github.action_path }}
        node index.js $GITHUB_WORKSPACE
