name: Major Release Tagger

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: cloudposse/github-action-major-release-tagger@initial
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
